# Generated by Django 2.0.8 on 2020-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This product is very unique.There has also discount too.There are a offer which is buy one get one free if you buy this product within 31 july.'),
            preserve_default=False,
        ),
    ]
